#!/bin/sh
USER=zacharyc_vps
HOST=vps37110.dreamhostps.com
DIR=/home/zacharyc_vps/zacharyc.com   # the directory where your web site files should go

# hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR} # this will delete everything on the server that's not in the local public folder 

hugo && rsync -avz public/ ${USER}@${HOST}:${DIR} # Hopefuly won't delete, but I'm downloading content to check first.

exit 0